# Generated by Django 2.1 on 2019-08-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='strict_measurement',
            field=models.BooleanField(default=False, verbose_name='Strictly measured'),
        ),
        migrations.AddField(
            model_name='source',
            name='online_version',
            field=models.URLField(blank=True, null=True),
        ),
    ]
