# Generated by Django 2.1 on 2019-08-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0002_auto_20190826_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractunit',
            name='standard_size',
            field=models.BooleanField(default=False, verbose_name='Standard size'),
        ),
    ]
