# Generated by Django 2.1 on 2019-09-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorn', '0004_auto_20190826_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseunit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='abstractunit',
            name='quantity',
            field=models.SmallIntegerField(choices=[(1, 'Mass'), (2, 'Volume')], default=2, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Reference'), (2, 'Inferred'), (3, 'Ambiguous'), (4, 'Asumption'), (5, 'Anomalous'), (6, 'Measured'), (-1, 'Error'), (-2, 'Irrelevant')], default=1, verbose_name='Status'),
        ),
    ]
